"""Cambia auto_logout a minutos de inactividad

Revision ID: 8b045093fba0
Revises: ddca3c3c2cb9
Create Date: 2025-09-04 23:07:48.681380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b045093fba0'
down_revision = 'ddca3c3c2cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_logout_minutes', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_column('auto_logout_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_logout_enabled', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('auto_logout_minutes')

    # ### end Alembic commands ###
