"""Añade campo de tema para modo nocturno a User

Revision ID: b46671e6930a
Revises: dcfb4d4adcb0
Create Date: 2025-09-04 23:51:59.181132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46671e6930a'
down_revision = 'dcfb4d4adcb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), server_default='light', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
