"""Implementa interruptor para auto-logout

Revision ID: dcfb4d4adcb0
Revises: 8b045093fba0
Create Date: 2025-09-04 23:14:44.183454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfb4d4adcb0'
down_revision = '8b045093fba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_logout_enabled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_logout_enabled')

    # ### end Alembic commands ###
